spring.application.name=backend
spring.datasource.url=jdbc:postgresql://pg-124d7ec2-gowrisankarramella3-7c24.i.aivencloud.com:24517/defaultdb?ssl=require&user=avnadmin&password=AVNS_zplX_esXIgLpcrKIAyN
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_zplX_esXIgLpcrKIAyN

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false